name: main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  build:
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/master'}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW-x86_64-v3, toolchain: mingw-w64-x86_64-v3-toolchain, prefix: mingw-x86_64-v3, can-fail: false }
        ]
    name: ${{ matrix.msystem }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      mingw_repo_sf: https://sourceforge.net/projects/mingw-w64-x86-64-v3/files/${{ matrix.prefix }}
      mingw_repo_gh: https://github.com/MehdiChinoune/MinGW-packages/releases/download/${{ matrix.prefix }}
      msys_repo: https://github.com/MehdiChinoune/MSYS2-packages/releases/download/msys-x86_64-v3
    steps:
      - name: Get Processor Info
        run : |
          Get-CIMInstance -Class Win32_Processor | Select-Object -Property Name
          echo $Env:NUMBER_OF_PROCESSORS
      - uses: actions/checkout@v2
        with:
          path: temp
          fetch-depth: 0

      # to match the autobuild environment
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install: VCS base-devel binutils pactoys-git
          update: true

      - name: Add staging repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[staging]\nServer = https://repo.msys2.org/staging/\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Add msys repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[msys-x86_64-v3]\nServer = ${{ env.msys_repo }}\nSigLevel = Never\n|' /etc/pacman.conf
      - name: Add ${{ matrix.msystem }} repo
        shell: msys2 {0}
        run: |
          sed -i '1s|^|[${{ matrix.prefix }}]\nServer = ${{ env.mingw_repo_gh }}\nServer = ${{ env.mingw_repo_sf }}\nSigLevel = Never\n|' /etc/pacman.conf

      - name: Update using staging, msys-x86_64-v3 and ${{ matrix.msystem }} repos
        run: |
          msys2 -c 'pacman --noconfirm -Suuy'
          msys2 -c 'pacman --noconfirm -Suu'

      - name: Install ${{ matrix.msystem }} toolchain
        run: |
          msys2 -c 'pacman --noconfirm -S ${{ matrix.toolchain }}'

      - name: Move Checkout
        run: |
          Copy-Item -Path ".\temp" -Destination "C:\_" -Recurse

      - name: CI-Build
        shell: msys2 {0}
        continue-on-error: ${{ matrix.can-fail }}
        env:
          MSYSTEM: ${{ matrix.msystem }}
          MINGW_ARCH: ${{ matrix.msystem }}
        run: |
          cd /C/_
          git config --global user.name "Mehdi Chinoune"
          git config --global user.email "mehdi.chinoune@hotmail.com"
          mkdir artifacts && cd artifacts
          repo-add ci.db.tar.gz && cd ..
          sed -i '1s|^|[ci]\nServer = file://'"$PWD"'/artifacts/\nSigLevel = Never\n|' /etc/pacman.conf
          pacman -Sy
          readarray -t pkgs <pkgs.txt
          for pkg in ${pkgs[@]}; do
            cd $pkg
            makepkg-mingw -s --noconfirm --skippgpcheck --nocheck
            repo-add ../artifacts/ci.db.tar.gz *.tar.zst
            cp *.tar.zst ../artifacts
            pacman -Sy
            cd ..
          done

      - name: Download myrepo database files
        run: |
          cd temp
          gh release download ${{ matrix.prefix }} -p '${{ matrix.prefix }}*' -D myrepo

      - name: Update local database files
        shell: msys2 {0}
        run: |
          repo-add temp/myrepo/${{ matrix.prefix }}.db.tar.gz /c/_/artifacts/*.pkg.tar.*
          rm temp/myrepo/*.old

      - name: Restore ssh private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Upload packages and database
        shell: bash
        run: |
          cd temp
          gh release upload ${{ matrix.prefix }} C:/_/artifacts/*.pkg.tar.* myrepo/* --clobber
          scp C:/_/artifacts/*.pkg.tar.* mchinoune@frs.sourceforge.net:/home/frs/project/mingw-w64-x86-64-v3/${{ matrix.prefix }}
          scp myrepo/* mchinoune@frs.sourceforge.net:/home/frs/project/mingw-w64-x86-64-v3/${{ matrix.prefix }}
